steps:
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']

    - name: 'gcr.io/cloud-builders/npm'
      args: ['run','lint']

    - name: 'gcr.io/cloud-builders/npm'
      args: ['run','build']

    - name: 'ubuntu'
      args: ['ls', '-la', 'build/']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '--no-cache', '-t', 'social-network-ui:latest', '.']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['tag', 'social-network-ui:latest', 'gcr.io/prenigmaplaces/social-network-ui:latest']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/prenigmaplaces/social-network-ui:latest']


images:
    - 'gcr.io/prenigmaplaces/social-network-ui:latest'
tags:
    - "vperminov-cloudbuild"
