export const RESET_GROUP_STATE = 'group/RESET_GROUP_STATE';
export const CREATE_GROUP_TITLE = 'group/CREATE_GROUP_TITLE';
export const RECEIVED_GROUP_DATA = 'group/RECEIVED_GROUP_DATA';
export const FETCH_GROUP_POSTS = 'group/FETCH_GROUP_POSTS';
export const SAVE_GROUP_POST_LIKE_UNLIKE = 'group/SAVE_GROUP_POST_LIKE_UNLIKE';
export const SAVE_GROUP_POST_COMMENT_LIKE_UNLIKE = 'group/SAVE_GROUP_POST_COMMENT_LIKE_UNLIKE';