export const LOAD_RECENT_RECEIVED_SENT_STARS = 'StarME/LOAD_RECENT_RECEIVED_SENT_STARS';
export const ADD_LIKE = 'StarME/ADD_LIKE';
export const SAVE_COMMENT_LIKE_UNLIKE = 'StarME/SAVE_COMMENT_LIKE_UNLIKE';